# Use the official nginx base image
FROM nginx:alpine

RUN apk update && apk add --no-cache curl && apk add --no-cache libcrypto3=3.5.1-r0


# Copy custom nginx config
COPY nginx.conf /etc/nginx/nginx.conf

# Remove the default Nginx page
RUN rm -rf /usr/share/nginx/html/*
COPY index.html /usr/share/nginx/html/index.html
